### PR TITLE
Add yunohost-firewall to list of firewalls

### PR DESCRIPTION
**Pull request by ZeHiro**
**Problem**

yunohost-firewall was not detected as a valid firewall
**Solution**

I added it to the list of firwalls

### CODE REVIEW

**Comment by ZeHiro** [comment]
I didn't see #6 , maybe my fix won't be enough

**Comment by ZeHiro** [comment]
Won't work. I close.

**Comment by gelnior** [comment]
We could have integrate it, at least for the record.

**Comment by ZeHiro** [comment]
In fact it is based on iptables, so I prefer waiting the check first works, before resubimitting

**Pull request closed without merging**
